### PR TITLE
Grammatical fixes/ Markdown Fixes

### PR DESCRIPTION
**Pull request by BaileyLawson**

### CODE REVIEW

**Comment by BaileyLawson** [comment]
Changes made to make PoSH style guide easier to read and follow.

**Comment by BaileyLawson** [comment]
Bump

**Comment by BaileyLawson** [comment]
Any chance this could get a review?

**Comment by Schwitzd** [comment]
great changes! 
it seems that this repo is dying :'(

**Comment by BaileyLawson** [comment]
> great changes!
> it seems that this repo is dying :'(

Thanks :) It's a shame, this guide is a valuable resource to the PowerShell community as far as I'm concerned

**Comment by darkoperator** [comment]
Will take a look at this today.

**Pull request merged**
