### PR TITLE
Update Function Structure.md

### PR DESCRIPTION
**Pull request by leesoh**
Moved brace to same line as per style guide.

### CODE REVIEW

**Comment by darkoperator** [comment]
/me breaths deeply as he thinks about the brace rule and that it should just be deleted and let people choose either method as he had on his original guide

**Comment by li-so** [comment]
I feel you. Although it is a *guide* so taking a stance one way or another seems reasonable, no?

**Comment by Jaykul** [comment]
@darkoperator *IF* we have a brace rule in the style guide, it should list a couple (K&R, OTBS, etc), and then say "pick one and stick with it" -- agreed?

However, in order to say that, we have to pick one for the guide itself!

**Comment by darkoperator** [comment]
Agree with ti :)

Sorry for the long time to reply, at work event in Vegas this week.

**Pull request merged**
