### PR TITLE
Update Code Layout and Formatting.md

### PR DESCRIPTION
**Pull request by leesoh**
Added explanations, removed option to drop lines (it's a guide, therefore dropping things is optional anyways).

### CODE REVIEW

**Comment by Xalorous** [comment]
This is my first attempt to suggest a change.  I hope this is the right place.  Small change suggested to fix it's/its issue.

In:
PowerShellPracticeAndStyle/Style Guide/Code Layout and Formatting.md

Last section uses "it's" and it should be "its"

**Comment by pixelrebirth** [comment]
While I approve of the CmdletBinding, I disagree that it adds:

"Enhanced parameters (e.g., mandatory)"

I have used [parameter(mandatory=$true)] many times without CmdletBinding--- if you are referring to something you you are positive it changes-- add that as an example instead of mandatory

**Comment by dlwyatt** [comment]
CmdletBinding is implied if you use any `[Parameter()]` attributes, but it's generally considered a good practice to include CmdletBinding anyway.

**Comment by pixelrebirth** [comment]
wow... your absolutely right. TIL

**Pull request closed without merging**
